##########
# Groups #
##########

GROUP_ALL = 'all'
GROUP_USERS = 'users'
GROUP_EMAIL_CONFIRMED = 'email_confirmed'
GROUP_AUTOPATROLLED = 'autopatrolled'
GROUP_PATROLLERS = 'patrollers'
GROUP_ADMINISTRATORS = 'administrators'
GROUP_BOTS = 'bots'
GROUP_RIGHTS_MANAGERS = 'rights_managers'

USER_GROUPS_IDS = [
    GROUP_ALL,
    GROUP_USERS,
    GROUP_EMAIL_CONFIRMED,
    GROUP_AUTOPATROLLED,
    GROUP_ADMINISTRATORS,
    GROUP_BOTS,
    GROUP_RIGHTS_MANAGERS,
]

##########
# Rights #
##########

RIGHT_READ_PAGES = 'read'
RIGHT_EDIT_PAGES = 'edit'

RIGHT_RENAME_PAGES = 'rename_pages'
RIGHT_DELETE_PAGES = 'delete_pages'
RIGHT_PROTECT_PAGES = 'protect_pages'
RIGHT_REVOKE = 'revoke'
RIGHT_VALIDATE_CHANGES = 'validate_changes'
RIGHT_HIDE_REVISIONS = 'hide_revisions'
RIGHT_BLOCK_USERS = 'block_users'
RIGHT_RENAME_USERS = 'rename_users'
RIGHT_EDIT_USERS_GROUPS = 'edit_users_groups'
RIGHT_EDIT_USER_PAGES = 'edit_user_pages'

NAMESPACE_RIGHTS = (
    RIGHT_READ_PAGES,
    RIGHT_EDIT_PAGES,
)

GLOBAL_RIGHTS = (
    RIGHT_RENAME_PAGES,
    RIGHT_DELETE_PAGES,
    RIGHT_PROTECT_PAGES,
    RIGHT_REVOKE,
    RIGHT_VALIDATE_CHANGES,
    RIGHT_HIDE_REVISIONS,
    RIGHT_BLOCK_USERS,
    RIGHT_RENAME_USERS,
    RIGHT_EDIT_USERS_GROUPS,
    RIGHT_EDIT_USER_PAGES,
)
