"""
Django settings for WikiPyProject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

import WikiPy.settings as wpy_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')duihc**n+1ft!ta^hme1(#r1vv(jze^i9p0ohr%_g-7!%efj5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'WikiPy.apps.WikiPyConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WikiPyProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WikiPyProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },  # TODO enable other DB managers
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'myproject',
    #     'USER': 'myprojectuser',
    #     'PASSWORD': 'password',
    #     'HOST': 'localhost',
    #     'PORT': '',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

USE_TZ = True

# WikiPy settings intialization.

AUTH_USER_MODEL = 'WikiPy.CustomUser'

wpy_settings.init(BASE_DIR)

LANGUAGE_CODE = wpy_settings.DEFAULT_LANGUAGE_CODE
TIME_ZONE = wpy_settings.TIME_ZONE
ALLOWED_HOSTS = wpy_settings.ALLOWED_HOSTS
DEFAULT_FROM_EMAIL = wpy_settings.FROM_EMAIL
EMAIL_SUBJECT_PREFIX = f'[{wpy_settings.PROJECT_NAME}] '
if wpy_settings.EMAIL_HOST:
    EMAIL_HOST = wpy_settings.EMAIL_HOST
if wpy_settings.EMAIL_PORT:
    EMAIL_PORT = wpy_settings.EMAIL_PORT
if wpy_settings.EMAIL_HOST_USER:
    EMAIL_HOST_USER = wpy_settings.EMAIL_HOST_USER
if wpy_settings.EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = wpy_settings.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = wpy_settings.EMAIL_USE_TLS
EMAIL_USE_SSL = wpy_settings.EMAIL_USE_SSL
if wpy_settings.EMAIL_SSL_KEYFILE is not None:
    EMAIL_SSL_KEYFILE = wpy_settings.EMAIL_SSL_KEYFILE
if wpy_settings.EMAIL_SSL_CERTFILE is not None:
    EMAIL_SSL_CERTFILE = wpy_settings.EMAIL_SSL_CERTFILE
if wpy_settings.EMAIL_TIMEOUT is not None:
    EMAIL_TIMEOUT = wpy_settings.EMAIL_TIMEOUT

if not wpy_settings.EMAIL_HOST:
    if DEBUG:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:  # Not in debug and no defined host, resort to dummy backend
        EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'WikiPy/static'),
]
STATIC_URL = '/static/'
