import abc as _abc
import importlib as _importlib
import logging as _logging
import time as _time
import typing as _typ

import django.urls as dj_urls


class Skin(_abc.ABC):
    def __init__(self, name: str, label: str):
        self.__name = name
        self.__label = label

    @property
    def name(self) -> str:
        return self.__name

    @property
    def label(self) -> str:
        return self.__label

    def get_internal_link(self, api, page_title: str, text: str = None, anchor: str = None, **url_params):
        ns_id, title = api.extract_namespace_and_title(page_title, ns_as_id=True)
        page_exists = api.page_exists(ns_id, title)
        url = dj_urls.reverse('page', kwargs={'raw_page_title': api.as_url_title(page_title)})

        if page_exists:
            if url_params == {}:
                if anchor:
                    url += '#' + anchor
            else:
                url += '?' + '&'.join([f'{p}={v}' for p, v in url_params.items()])
        elif ns_id != -1:
            url += '?action=edit&redlink=1'

        return self._format_link(api, url, text, page_exists)

    @_abc.abstractmethod
    def _format_link(self, api, url: str, text: str, page_exists: bool):
        pass

    def render_wikicode(self, api, parsed_wikicode) -> str:
        """
        Renders the given parsed wikicode.
        :param parsed_wikicode: The parsed wikicode to render.
        :type parsed_wikicode: django_wiki.api.ParsedWikicode
        :return: The parsed wikicode.
        """
        start = _time.time()
        render = self._render_wikicode_impl(api, parsed_wikicode)
        total = (_time.time() - start) * 1000
        comment = f"""
<!--
Page generated by WikiPy in {total:0.4} ms.
Skin: {self.label}
-->"""

        return render + comment

    @_abc.abstractmethod
    def _render_wikicode_impl(self, api, parsed_wikicode) -> str:
        """
        Renders the given parsed wikicode.

        :param parsed_wikicode: The parsed wikicode to render.
        :type parsed_wikicode: django_wiki.api.ParsedWikicode
        :return: The parsed wikicode.
        """
        pass


_LOADED_SKINS = {}


def load_skin(name: str):
    try:
        module = _importlib.import_module('._' + name, package=__name__)
        skin = module.load_skin()
        _LOADED_SKINS[skin.name] = skin
    except ModuleNotFoundError:
        _logging.warning(f'unknown skin name "{name}", ignored')


def get_skin(name: str) -> Skin:
    if name in _LOADED_SKINS:
        return _LOADED_SKINS[name]
    return _LOADED_SKINS['default']


def get_loaded_skins_names() -> _typ.List[str]:
    return sorted(_LOADED_SKINS.keys())
